### ISSUE TITLE
[improvement] Please consider including tag management functions in the package

### ISSUE THREAD

**Issue by asitemade4u** [cboettig/minio#13]
Hi Carl,
Following our previous discussions (#12), I have created wrapper functions in R to manage tags using your package.

But considering the "oddities" of tag implementation in Minio (see below), that wrapping creates a lot of additional and fairly intricate overhead to decode the output of the native `mc` commands called by your `mc`: basically, fetching information from a verbose terminal like output.

For example, here is the output of `minioclient::mc(command = glue::glue("tag list {thebkt}"))`:

1. if **no tags** are found:
```bash
Error in `processx::run(binary, args, ...)`:
! System command 'mc' failed
---
Exit status: 1
Stderr:
mc: <ERROR> No tags found  for http://192.168.1.221:9000/play-tykcnrwokcir: check 'mc tag set --help' on how to set tags.
---
Type .Last.error to see the more details.
```

2. If **tags are found**:
```bash
$status
[1] 0
$stdout
[1] "Name : http://192.168.1.221:9000/play-qahrxqsqmccg/\nkey  : zaza\nsrc  : zazou\n"
$stderr
[1] ""
$timeout
[1] FALSE
```
So, if you have time, would you consider creating these commands in `minioclient`, please?

- `mc_tagadd`: adds tags **cumulatively** and deduplicates the tags to be added against the possibly existing tags in the bucket/file
- `mc_taglis`: outputs a vector of tags
- `mc_tagrem`: removes tags from the bucket/file

Of course:
- the names are up to you
- and I am happy to test your implementation.

Lastly, as a reminder:
- each bucket/file can have at most 10 tags
- tags are saved as a `key=value` pair
- two tags in the same bucket/file cannot have the same `key`
- two tags in the same bucket/file cannot be duplicates
- adding tag(s) to a bucket/file erases all previously assigned tags

Thanks,
S.

**Comment by cboettig** [comment]
that's a good idea.  I think it would be natural for the R user to specify tags as a named character vector, (or list) e.g. 

```
mc_tag_add("alias/path", tags = c(key1 = "value1", key2 = "value2")
```

Thoughts?  I think the syntax for `mc_tag_list()` and `mc_tag_rm` would be simpler since they just take the path.    


I haven't really leveraged tags much -- if you don't mind me asking, can you outline the use cases for what tags let you do?   Are they for access control? listing? other operations? Thanks!

p.s. the bug-fix release for 0.0.6 is now on CRAN.

**Comment by cboettig** [comment]
that's cool, thanks for sharing.  The versioning abilities in minio / s3 are compelling, and maybe we need more explicit support for those too.  Not to meddle, but tags for metadata make me a little nervous, especially as they are easily overwritten and harder to read/view without a dedicated client tool -- my instinct would be to use an explicit metadata file that is committed to the bucket, which could be versioned to prevent loss and could be easily read over a standard https interface.  Of course one could do both as well.  It does seem like tags would be the easiest way to manage fine-grained access control.  

re contentid -- thanks, I've been hoping to find a way for those tools to play more easily with each-other.  as you know, minio has md5 sums for all contents, I wish I had a good way to query across an entire minio bucket by checksum, hash://md5/xxxx ...

**Comment by cboettig** [comment]
btw, [huggingface](https://huggingface.co/datasets) is a pretty convenient free platform for git+LFS w/o any size/billing constraints that GitHub imposes :smile:
